[package]
name = "merkle_membership"
version = "0.1.0"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "0.18.0", default-features = false }
shared = { path = "../../../shared" }
