[package]
name = "methods"
version = "0.1.0"
edition = "2021"

[build-dependencies]
risc0-build = { version = "0.18.0" }

[package.metadata.risc0]
methods = [
    "sha",
    "blake3",
    "assert",
    "fib",
    "merkle",
    "merkle_membership",
]
